<?

include('include.php');

if (!isset($_GET['type'])) {

	die("Sorry, 'Type' is not set");

}

if (!isset($_GET['pl'])) {

	die("Sorry, 'playerList' is not set");

}

if (strlen($_GET['pl']) == 0) {

	die("Sorry, 'playerList' is empty!");
	
}

$idarray = explode(',', $_GET['pl']);
$newlist = array();

foreach($idarray as $id) {

	$id += 0;
	if ($id > 0) {
		$newlist[] = $id;
		continue;
	}
	
	die("Sorry, 'playerList' has invalid entries.");

}

$newlist = implode(',', $newlist);

$res = $db->query("

	$sqlgenselect
	,server.name as servername
	,server.id as serverid

	from player

	LEFT JOIN server ON server.id = player.curserverid

	where player.id in ($newlist)

	order by rank

");

if (isset($_GET['ss'])) {

	$ss = $_GET['ss'];

} else {

	$ss = '';

}

if ($ss == '') $ss = 'style-export.php';

header("Content-type: text/html; charset=utf-8");
header("Cache-Control: no-cache");

?>
<html>
<head>
<title></title>
<base target="_top">
<base href="http://acssr.slowchop.com/">
<style type="text/css">@import "<?=$ss?>";</style>
</head>
<body class="acssr">

<?
dumpTable($res, array('export'=>true, 'small'=>true, 'total'=>false, 'format'=>$_GET['type']));
?>

<div>Stats generated by <a href="http://acssr.slowchop.com/">ACSSR</a></div>

</body>
</html>

